// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id your-project-id > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          plan: string
          subdomain: string | null
          custom_domain: string | null
          timezone: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          plan?: string
          subdomain?: string | null
          custom_domain?: string | null
          timezone?: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          plan?: string
          subdomain?: string | null
          custom_domain?: string | null
          timezone?: string
          created_at?: string
        }
      }
      tenant_users: {
        Row: {
          tenant_id: string
          user_id: string
          role: 'admin' | 'user'
          created_at: string
        }
        Insert: {
          tenant_id: string
          user_id: string
          role?: 'admin' | 'user'
          created_at?: string
        }
        Update: {
          tenant_id?: string
          user_id?: string
          role?: 'admin' | 'user'
          created_at?: string
        }
      }
      leads: {
        Row: {
          id: string
          tenant_id: string
          created_by: string | null
          name: string
          email: string | null
          phone: string | null
          source: string | null
          status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
          company: string | null
          notes: string | null
          tags: string[]
          value: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by?: string | null
          name: string
          email?: string | null
          phone?: string | null
          source?: string | null
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
          company?: string | null
          notes?: string | null
          tags?: string[]
          value?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string | null
          name?: string
          email?: string | null
          phone?: string | null
          source?: string | null
          status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
          company?: string | null
          notes?: string | null
          tags?: string[]
          value?: number
          created_at?: string
          updated_at?: string
        }
      }
      activities: {
        Row: {
          id: string
          tenant_id: string
          lead_id: string
          user_id: string | null
          type: string
          title: string | null
          body: string | null
          due_at: string | null
          done: boolean
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          lead_id: string
          user_id?: string | null
          type: string
          title?: string | null
          body?: string | null
          due_at?: string | null
          done?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          lead_id?: string
          user_id?: string | null
          type?: string
          title?: string | null
          body?: string | null
          due_at?: string | null
          done?: boolean
          created_at?: string
        }
      }
      message_templates: {
        Row: {
          id: string
          tenant_id: string
          name: string
          channel: 'email' | 'sms' | 'whatsapp'
          subject: string | null
          body: string
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          channel: 'email' | 'sms' | 'whatsapp'
          subject?: string | null
          body: string
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          channel?: 'email' | 'sms' | 'whatsapp'
          subject?: string | null
          body?: string
          created_at?: string
        }
      }
      message_outbox: {
        Row: {
          id: string
          tenant_id: string
          lead_id: string | null
          channel: 'email' | 'sms' | 'whatsapp'
          to_address: string
          subject: string | null
          body: string
          status: 'queued' | 'sent' | 'failed'
          error: string | null
          scheduled_at: string
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          lead_id?: string | null
          channel: 'email' | 'sms' | 'whatsapp'
          to_address: string
          subject?: string | null
          body: string
          status?: 'queued' | 'sent' | 'failed'
          error?: string | null
          scheduled_at?: string
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          lead_id?: string | null
          channel?: 'email' | 'sms' | 'whatsapp'
          to_address?: string
          subject?: string | null
          body?: string
          status?: 'queued' | 'sent' | 'failed'
          error?: string | null
          scheduled_at?: string
          sent_at?: string | null
          created_at?: string
        }
      }
      automations: {
        Row: {
          id: string
          tenant_id: string
          name: string
          is_active: boolean
          trigger_type: string
          from_status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          to_status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          action_channel: 'email' | 'sms' | 'whatsapp'
          template_id: string
          delay_minutes: number
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          is_active?: boolean
          trigger_type: string
          from_status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          to_status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          action_channel: 'email' | 'sms' | 'whatsapp'
          template_id: string
          delay_minutes?: number
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          is_active?: boolean
          trigger_type?: string
          from_status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          to_status?: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost' | null
          action_channel?: 'email' | 'sms' | 'whatsapp'
          template_id?: string
          delay_minutes?: number
          created_at?: string
        }
      }
      pipeline_stages: {
        Row: {
          id: number
          key: string
          sort_order: number
        }
        Insert: {
          id?: number
          key: string
          sort_order: number
        }
        Update: {
          id?: number
          key?: string
          sort_order?: number
        }
      }
      profiles: {
        Row: {
          user_id: string
          display_name: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          display_name?: string | null
          created_at?: string
        }
        Update: {
          user_id?: string
          display_name?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      v_leads_by_status: {
        Row: {
          tenant_id: string
          status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
          total: number
        }
      }
      v_current_user_tenants: {
        Row: {
          tenant_id: string
        }
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      lead_status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'won' | 'lost'
      msg_channel: 'email' | 'sms' | 'whatsapp'
      msg_status: 'queued' | 'sent' | 'failed'
      user_role: 'admin' | 'user'
    }
  }
}